### ISSUE TITLE
Experiences setting up pygccxml on OSX

### ISSUE THREAD

**Issue by MarkOates** [CastXML/pygccxml#31]
I wanted to drop a log on my experiences for building `pygccxml` for the first time.  It wasn't completely seamless but I managed to overcome a few snags and I'm hoping it might help future development of this really awesome library.

Initially, compiling, installing, and configuring the dependencies was a bit daunting, particularly considering that it takes about 45 minutes to compile Clang and I was still uncertain if I had installed or configured all the correct components.  Despite poking around in that, I came across https://github.com/thewtex/CastXMLSuperbuild which I would recommend to _anybody_ installing `pygccxml` for the first time.   I think a link should be included in the main `pygccxml` `README.md`.

Despite having both GCC-XML and CastXML on my system, I found that `pygccxml` defaulted to using `gccxml` when calling `utils.find_xml_generator()` in the examples.  I think `castxml` should be used by default.  This lead to a bit of confusion, and I think it should be documented somewhere that strings `name='gccxml'` and `name='castxml'` are options for names.  Maybe a nice message upon invocation `using the 'gccxml' backend` or something similar would also be nice.

Also, I had to manually set `utils.find_xml_generator(name='castxml')` in order to get proper usage of `parser.xml_generator_configuration_t(compiler='gcc' ...)`. Without having more insight, it seemed that with the GCC-XML `pygccxml` could not operate using a _g++_ compiler, and only seemed to work with pure C _gcc_ code.  `pygccxml` would throw errors when I would simply add `#include <string>` at the top of an example program and it took a bit of investigation.

After trying to manually use CastXML from the command line, was I able to clue in that the issue was closer to `pygccxml` implementation designation of `castxml` and `gccxml`.  (It's also _very_ likely that my compiler configurations are a bit mangled as well, as `c++` and `g++` are aliases Clang on OSX).  I also had to add the location of the executable for `castxml` to my `PATH`, and that step was not included or documented in the CastXMLSuperbuild process.

Also, the `parser.xml_generator_configuration_t` argument `include_paths` is an array even though it is documented as a string delimited by `;`.

I felt like the documentation needed _just one more tutorial_ that included and example with a compiler definition, include directories, and cflags.

Anyway, thank you guys for making this library.  I hope my experience helps in some way.

**Comment by iMichka** [comment]
Hi

> I wanted to drop a log on my experiences for building pygccxml for the first time. It wasn't completely seamless but I managed to overcome a few snags and I'm hoping it might help future development of this really awesome library.

First of all, thanks for the feedback. It is really appreciated. Things that seem obvious to the developers of a project are not always obvious for the users.

> Initially, compiling, installing, and configuring the dependencies was a bit daunting, particularly considering that it takes about 45 minutes to compile Clang and I was still uncertain if I had installed or configured all the correct components. Despite poking around in that, I came across https://github.com/thewtex/CastXMLSuperbuild which I would recommend to anybody installing pygccxml for the first time. I think a link should be included in the main pygccxml README.md.

Installing CastXML is the most difficult part. GCC-XML had the advantage that it was packaged under debian, so easily installable under Linux. CastXML is quite new (~1 year now), so there are not many packages for it out there. New platforms are now also better supported, like OS X and Windows compilers, but this adds more work because this means writing an install tutorial for 3 platforms.

Initially there was never a documentation on how to build GCC-XML here, so I did not write any for CastXML. I know that this is a big hurdle to start with and a lot of people get frustrated at that point. I think I will extend the documentation for this point, but it may take some time.

Also, there is a plan to have a homebrew formula for OS X. I am waiting that CastXML gets it's 1.0 tag, because they stopped accepting head-only formulas at homebrew ...

> Despite having both GCC-XML and CastXML on my system, I found that pygccxml defaulted to using gccxml when calling utils.find_xml_generator() in the examples. I think castxml should be used by default. This lead to a bit of confusion, and I think it should be documented somewhere that strings name='gccxml' and name='castxml' are options for names. Maybe a nice message upon invocation using the 'gccxml' backend or something similar would also be nice.

The version 1.7.0 of pygccxml is the first one to support CastXML. I was rather conservative here and defaulted to GCC-XML. I think I'll default to CastXML for version 1.8.0. Adding an info message is a good idea.

> Also, I had to manually set utils.find_xml_generator(name='castxml') in order to get proper usage of parser.xml_generator_configuration_t(compiler='gcc' ...). Without having more insight, it seemed that with the GCC-XML pygccxml could not operate using a g++ compiler, and only seemed to work with pure C gcc code. pygccxml would throw errors when I would simply add #include <string> at the top of an example program and it took a bit of investigation.

If you were on OS X, GCC-XML is just not working with something else than gcc 4.2 or older. Anyway it is not really recommended to use GCC-XML anymore. I will probably even drop it's support completely later; but that is a lot of work (that would simplify the code though).

> After trying to manually use CastXML from the command line, was I able to clue in that the issue was closer to pygccxml implementation designation of castxml and gccxml. (It's also very likely that my compiler configurations are a bit mangled as well, as c++ and g++ are aliases Clang on OSX). I also had to add the location of the executable for castxml to my PATH, and that step was not included or documented in the CastXMLSuperbuild process.

If you have multiple compilers/gccxml/castxml installed, it is very difficult for the find_xml_generator setup to know what to do. The default setups shown in the examples are for the most easiest case.

You still need to pass the right flags and paths everywhere, because I can not guess the toolchain a user would want to use. Especially from python (and even from bash); there is no way to discriminate between different versions of compilers ... for example the clang delivered by Apple is a patched Clang which does not follow the official release ... so you newer know what you end up with. It is better the users tells pygccxml what he wants to use.

> Also, the parser.xml_generator_configuration_t argument include_paths is an array even though it is documented as a string delimited by ;.

I'll have a look.

> I felt like the documentation needed just one more tutorial that included and example with a compiler definition, include directories, and flags.

The current examples are quite new. I wrote them not so long ago. Before there was only one example and the API docs. I hope I can find some time this year to extend them.

> Anyway, thank you guys for making this library. I hope my experience helps in some way.

Thanks. I'll keep this bug open until I have addressed the mentioned points. Thank you again for the feedback.

**Comment by MarkOates** [comment]
Thank you!

**Comment by jackwasey** [comment]
I'm battling with this same problem (via py++).
There is still code to split includes based on semicolons, but I don't appear to hit that code path.

**Comment by iMichka** [comment]
Closing this. I made changes here and there around documentation. I hope this will help people get started.

I would rather prefer a pull request to fix the remaining documentation quirks. Thanks for the initial report!

**Comment by wzawisa** [comment]
I am having issues related to this. I am using pygccxml like such below:

```
# Configurations for parser
generator_path = "/usr/local/bin/castxml"
generator_name = "castxml"
compiler = "gcc"
compiler_path = "/usr/bin/gcc"
include_collection = ['/usr/local/include/']

# Create configuration for CastXML
xml_generator_config = parser.xml_generator_configuration_t(
    xml_generator_path=generator_path,
    xml_generator=generator_name,
    compiler=compiler,
    compiler_path=compiler_path,
    include_paths=include_collection
)
```

I am running this on MacOS Catalina (10.15.6) with GCC 10.1 and CastXML installed. My python setup is using a virtual environment with Python 3.7.4. When I run the parser, it does not find the stat.h header and gives me the following error:

```
INFO Parsing source file "/path/to/file/header.h" ... 
"/path/to/file/header.h":3:10: fatal error: 
      cannot open file './sys/stat.h': No such file or directory
#include <sys/stat.h>
```

I have tried searching for the path of the header on my local machine and adding it to the $CPATH but the error still persists. Additionally, I have included the include path that leads to the directory where `sys/stat.h` exists into the config but the error still persists. My initial thought is that is only looking in the current directory for the header since it is saying "./sys" in the path. Has anyone else had this issue or know of any solutions? Thanks!

**Comment by iMichka** [comment]
This might be related to https://github.com/CastXML/CastXML/issues/176
